# kindly generated by appropriated Rails generator
Mailjet.configure do |config|
  config.api_key = ENV['MAILER_API_KEY']
  config.secret_key = ENV['MAILER_SECRET']
  config.default_from = 'cpfergus1@gmail.com'
end
